version: '3'

services:
  app:
    build: .
    container_name: it-patagonia-companies
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - database
      - cache

  database:
    image: postgres
    container_name: it-patagonia-companies-database
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command:
        [
            "-c",
            "log_statement=none",
            "-c",
            "log_destination=stderr"
        ]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  cache:
    image: redis:alpine
    container_name: it-patagonia-companies-redis
    ports:
      - "${CACHE_PORT}:${CACHE_PORT}"
    environment:
      REDIS_HOST: ${CACHE_HOST}"
      REDIS_PORT: ${CACHE_PORT}"
    volumes:
      - cache_data:/data

volumes:
  postgres_data:
  cache_data:
